= My aports
:source-language: sh
:repo-name: aports
:repo-branch: v3.21
:gh-name: kiurchv/{repo-name}
:gh-branch: main
:key-file: jakub@jirutka.cz-655775c4.rsa.pub
:repos-uri: https://kiurchv.xyz/aports

ifdef::env-github[]
image:https://github.com/{gh-name}/actions/workflows/release.yml/badge.svg?branch={gh-branch}[Build Status, link=https://github.com/{gh-name}/actions/workflows/release.yml?branch={gh-branch}]
endif::env-github[]

This repository contains aports that are not merged in the official https://alpinelinux.org[Alpine Linux] repository yet or don’t adhere to Alpine polices.
Packages are automatically built on https://github.com/{gh-name}/actions[GitHub Actions] for `x86_64` and `aarch64` architectures and published on {repos-uri} via GitHub Pages.

The *main branch* targets Alpine Linux *{repo-branch}*.
Aports for older Alpine https://alpinelinux.org/releases/[release branches] are in the same named branches in this repository, e.g. v3.15.
Alpine Edge (aka unstable, development branch) is not supported.


== Repositories


=== Backports

* {repos-uri}/{repo-branch}/backports

Aports from the official Alpine repositories backported from edge to {repo-branch}.


=== User

* {repos-uri}/{repo-branch}/user

My aports that are not available in the official Alpine repository.


=== Non-free

* {repos-uri}/{repo-branch}/non-free

Aports of non free or proprietary software.


== How to use

. Add security key of this repository to your `/etc/apk/keys`:
+
[source, subs="attributes"]
----
cd /etc/apk/keys
wget https://raw.githubusercontent.com/{gh-name}/{gh-branch}/.keys/{key-file}
----

. Add repositories that you want to use (see above) to `/etc/apk/repositories`.


== Git Hooks

You can find some useful git hooks in the `.githooks` directory.
To use them, run the following command after cloning this repository:

[source, sh]
git config --local core.hooksPath .githooks


== Acknowledgements

* https://github.com/jirutka[@jirutka] for his https://github.com/jirutka/user-aports[user-aports] repo — this README template and CI workflow and pre-commit hook was derived from his work
* https://github.com/ivanvc[@ivanvc] and https://github.com/ivanvc/abuild-releaser-action[abuild-releaser-action] project for the idea to deploy build artifacts to GitHub packages
* https://github.com/yKicchan[@yKicchan] for https://github.com/yKicchan/generate-directory-listing-action[generate-directory-listing-action] which was used to generate HTML directory listings for published packages


== License

This readme, abuilds and support scripts are licensed under http://opensource.org/licenses/MIT[MIT License].
